version: '3.8'

services:
  app:
    build: .
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    networks:
      - app-network

  swag:
    image: lscr.io/linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Stockholm
      - URL=luns.luns.se
      - SUBDOMAINS=
      - VALIDATION=dns
      - DNSPLUGIN=cloudflare
      - STAGING=true
      - EMAIL=henrik.soderstrom@outlook.com
    volumes:
      - ./swag:/config
    ports:
      - "443:443"
      - "80:80"
    restart: unless-stopped
    depends_on:
      - app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge